/**
 * Deterministic client-type generator from the API contract (ADR-0003).
 *
 * Reads `docs/api/openapi.yaml` (generated by `apps/api/scripts/generate-openapi.ts`
 * from the actual NestJS controllers) and emits
 * `packages/shared-types/src/generated/api-contract.ts`.
 *
 * The output is a build artifact: NEVER hand-edit either file.
 * Regenerate: pnpm gen:openapi && pnpm gen:types
 *
 * The structural envelope generics (`ApiSuccess<T>`, `ApiError`,
 * `ApiResponse<T>`) cannot be expressed in OpenAPI; they are emitted
 * from the fixed template below and are documented in docs/07_API.md §3.
 *
 * Run: pnpm gen:types   (from the repository root)
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { load } from 'js-yaml';

interface SchemaObject {
  type?: string;
  enum?: string[];
  properties?: Record<string, SchemaObject>;
  required?: string[];
  $ref?: string;
  nullable?: boolean;
  items?: SchemaObject;
  additionalProperties?: unknown;
  description?: string;
  format?: string;
}

interface OpenApiDocument {
  components?: { schemas?: Record<string, SchemaObject> };
}

const REPO_ROOT = join(__dirname, '..');
const INPUT_PATH = join(REPO_ROOT, 'docs', 'api', 'openapi.yaml');
const OUTPUT_PATH = join(REPO_ROOT, 'packages', 'shared-types', 'src', 'generated', 'api-contract.ts');

function refName(ref: string | undefined): string | undefined {
  if (ref === undefined) {
    return undefined;
  }
  const parts = ref.split('/');
  return parts[parts.length - 1];
}

function propertyType(schema: SchemaObject): string {
  if (schema.$ref !== undefined) {
    const refType = refName(schema.$ref) ?? 'unknown';
    return schema.nullable === true ? `${refType} | null` : refType;
  }
  if (schema.enum !== undefined) {
    return schema.enum.map((v) => `'${v}'`).join(' | ');
  }
  if (schema.type === 'object') {
    if (schema.properties === undefined) {
      // Free-form object: honor a typed additionalProperties when present.
      if (typeof schema.additionalProperties === 'object' && schema.additionalProperties !== null) {
        return `Record<string, ${propertyType(schema.additionalProperties as SchemaObject)}>`;
      }
      return 'Record<string, unknown>';
    }
    const required = new Set(schema.required ?? []);
    const members = Object.entries(schema.properties).map(([key, prop]) => {
      const opt = required.has(key) ? '' : '?';
      return `${key}${opt}: ${propertyType(prop)}`;
    });
    if (schema.additionalProperties === true) {
      members.push('[key: string]: unknown');
    }
    const body = members.join('; ');
    return schema.nullable === true ? `{ ${body} } | null` : `{ ${body} }`;
  }
  let base: string;
  switch (schema.type) {
    case 'string':
      base = 'string';
      break;
    case 'integer':
    case 'number':
      base = 'number';
      break;
    case 'boolean':
      base = 'boolean';
      break;
    case 'array':
      base = `Array<${schema.items !== undefined ? propertyType(schema.items) : 'unknown'}>`;
      break;
    default:
      base = 'unknown';
  }
  return schema.nullable === true ? `${base} | null` : base;
}

function emitSchema(name: string, schema: SchemaObject): string {
  // Alias schema (e.g. MeDto -> AuthUserDto).
  if (schema.$ref !== undefined && schema.type === undefined) {
    return `export type ${name} = ${refName(schema.$ref)};`;
  }
  // String enum.
  if (schema.enum !== undefined && schema.type === 'string') {
    return `export type ${name} = ${schema.enum.map((v) => `'${v}'`).join(' | ')};`;
  }
  // Object interface.
  if (schema.type === 'object') {
    const lines: string[] = [];
    if (schema.description !== undefined) {
      lines.push(...schema.description.split('\n').map((l) => ` * ${l.trim()}`.trimEnd()));
    }
    const header = lines.length > 0 ? `/**\n${lines.join('\n')}\n */\n` : '';
    const members: string[] = [];
    const required = new Set(schema.required ?? []);
    if (schema.properties !== undefined) {
      for (const [key, prop] of Object.entries(schema.properties)) {
        const opt = required.has(key) ? '' : '?';
        members.push(`  ${key}${opt}: ${propertyType(prop)};`);
      }
    }
    if (schema.additionalProperties === true) {
      members.push('  [key: string]: unknown;');
    }
    return `${header}export interface ${name} {\n${members.join('\n')}\n}`;
  }
  return `export type ${name} = unknown; // unsupported schema shape`;
}

const TEMPLATE_FOOTER = `// -----------------------------------------------------------------------------
// Structural envelopes. These are language-level generics and cannot be
// expressed in OpenAPI; their wire shape is documented in docs/07_API.md §3.
// -----------------------------------------------------------------------------

/** Standard success envelope. */
export interface ApiSuccess<T> {
  data: T;
  meta?: ApiMeta;
}

/** Canonical error envelope. */
export interface ApiError {
  error: {
    code: ErrorCode;
    message: string;
    fields?: Record<string, string>;
  };
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;
`;

function main(): void {
  const doc = load(readFileSync(INPUT_PATH, 'utf8')) as OpenApiDocument;
  const schemas = doc.components?.schemas ?? {};
  const names = Object.keys(schemas).sort();

  const sections: string[] = [];
  for (const name of names) {
    sections.push(emitSchema(name, schemas[name]));
  }

  const output = `/**
 * AUTO-GENERATED from docs/api/openapi.yaml via scripts/gen-types.ts
 * (ADR-0003). DO NOT EDIT — regenerate with:
 *
 *   pnpm gen:openapi && pnpm gen:types
 *
 * Contract source of truth: docs/07_API.md.
 */

${sections.join('\n\n')}

${TEMPLATE_FOOTER}`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[gen:types] wrote ${OUTPUT_PATH} (${String(output.length)} bytes, ${String(names.length)} schemas)`);
}

main();
